import type { Food, Stall } from './types';

export const demoStalls: Stall[] = [
  { _id: 'demo-golden-bites', stallName: 'Golden Bites', slug: 'golden-bites', batch: 'Batch 2026-A', description: 'Comfort-food favourites served hot from the fairground grill.', image: { url: '/images/chicken-burger.webp' } },
  { _id: 'demo-spice-street', stallName: 'Spice Street', slug: 'spice-street', batch: 'Batch 2024-C', description: 'Bright, spicy street food made for an evening at the fair.', image: { url: '/images/shan-noodles.webp' } },
  { _id: 'demo-sweet-corner', stallName: 'Sweet Corner', slug: 'sweet-corner', batch: 'Batch 2023-D', description: 'Small-batch sweets and chilled drinks for the walk home.', image: { url: '/images/brownie-tea.webp' } },
];

export const demoFoods: Food[] = [
  { stallFoodId: 'demo-burger', stallId: 'demo-golden-bites', foodId: 'demo-food-burger', stallName: 'Golden Bites', stallBatch: 'Batch 2026-A', food: { name: 'Classic Chicken Burger', description: 'Crispy chicken, slaw and house sauce.', category: 'Meals', image: { url: '/images/chicken-burger.webp' } }, eventDayPrice: 5000, discount: { type: 'percentage', value: 10 }, preorderPrice: 4500, ticketLimit: 80, ticketsRemaining: 48, isAvailable: true, demoImage: '/images/chicken-burger.webp' },
  { stallFoodId: 'demo-fries', stallId: 'demo-golden-bites', foodId: 'demo-food-fries', stallName: 'Golden Bites', stallBatch: 'Batch 2026-A', food: { name: 'Seasoned Fries', description: 'Hot, crisp fries with a savoury spice mix.', category: 'Snacks', image: { url: '/images/chicken-burger.webp' } }, eventDayPrice: 2500, discount: { type: 'fixed', value: 300 }, preorderPrice: 2200, ticketLimit: 100, ticketsRemaining: 63, isAvailable: true, demoImage: '/images/chicken-burger.webp' },
  { stallFoodId: 'demo-noodles', stallId: 'demo-spice-street', foodId: 'demo-food-noodles', stallName: 'Spice Street', stallBatch: 'Batch 2024-C', food: { name: 'Shan Noodle Cup', description: 'A warm Shan-style noodle cup with a gentle kick.', category: 'Meals', image: { url: '/images/shan-noodles.webp' } }, eventDayPrice: 4500, discount: { type: 'percentage', value: 15 }, preorderPrice: 3825, ticketLimit: 90, ticketsRemaining: 29, isAvailable: true, demoImage: '/images/shan-noodles.webp' },
  { stallFoodId: 'demo-skewers', stallId: 'demo-spice-street', foodId: 'demo-food-skewers', stallName: 'Spice Street', stallBatch: 'Batch 2024-C', food: { name: 'Spicy Chicken Skewers', description: 'Charred chicken skewers with chilli glaze.', category: 'Grill', image: { url: '/images/shan-noodles.webp' } }, eventDayPrice: 4000, discount: { type: 'percentage', value: 15 }, preorderPrice: 3400, ticketLimit: 75, ticketsRemaining: 18, isAvailable: true, demoImage: '/images/shan-noodles.webp' },
  { stallFoodId: 'demo-brownie', stallId: 'demo-sweet-corner', foodId: 'demo-food-brownie', stallName: 'Sweet Corner', stallBatch: 'Batch 2023-D', food: { name: 'Chocolate Brownie', description: 'A rich, soft-centred chocolate brownie.', category: 'Desserts', image: { url: '/images/brownie-tea.webp' } }, eventDayPrice: 3000, discount: { type: 'fixed', value: 300 }, preorderPrice: 2700, ticketLimit: 50, ticketsRemaining: 12, isAvailable: true, demoImage: '/images/brownie-tea.webp' },
  { stallFoodId: 'demo-milk-tea', stallId: 'demo-sweet-corner', foodId: 'demo-food-tea', stallName: 'Sweet Corner', stallBatch: 'Batch 2023-D', food: { name: 'Myanmar Milk Tea', description: 'Creamy tea poured over ice.', category: 'Drinks', image: { url: '/images/brownie-tea.webp' } }, eventDayPrice: 2500, discount: { type: 'percentage', value: 10 }, preorderPrice: 2250, ticketLimit: 120, ticketsRemaining: 76, isAvailable: true, demoImage: '/images/brownie-tea.webp' },
];
